apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: id8x6gdvi-python
  janus-idp.io/tekton: id8x6gdvi-python
  backstage.io/kubernetes-id: id8x6gdvi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: id8x6gdvi-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
