apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: id8x6gdvi-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: id8x6gdvi-python 
  name: id8x6gdvi-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: id8x6gdvi-python 
